# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'CV_test' do

platform :ios, "7.0"

#pod update --no-repo-update
pod 'OpenCV', '2.4.9'

end

